logging:
  level:
    root: ERROR
    org.springframework.ai: trace

spring:
  application:
    name: notch-chatbot
  ai:
    openai:
          api-key: ${API_KEY}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: postgres
    password: password

server:
  port: 5050
